// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: graph_snapshot.proto
// Protobuf C++ Version: 6.33.4

#include "graph_snapshot.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace request {

inline constexpr VertexAdj::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        out_{},
        in_{},
        tx_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR VertexAdj::VertexAdj(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(VertexAdj_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VertexAdjDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VertexAdjDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VertexAdjDefaultTypeInternal() {}
  union {
    VertexAdj _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VertexAdjDefaultTypeInternal _VertexAdj_default_instance_;

inline constexpr MergedOrderHash::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        node_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        hash_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR MergedOrderHash::MergedOrderHash(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MergedOrderHash_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MergedOrderHashDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MergedOrderHashDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MergedOrderHashDefaultTypeInternal() {}
  union {
    MergedOrderHash _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MergedOrderHashDefaultTypeInternal _MergedOrderHash_default_instance_;

inline constexpr GraphSnapshot::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        adj_{},
        merged_order_{},
        node_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR GraphSnapshot::GraphSnapshot(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GraphSnapshot_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GraphSnapshotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GraphSnapshotDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GraphSnapshotDefaultTypeInternal() {}
  union {
    GraphSnapshot _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GraphSnapshotDefaultTypeInternal _GraphSnapshot_default_instance_;
}  // namespace request
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_graph_5fsnapshot_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_graph_5fsnapshot_2eproto = nullptr;
const ::uint32_t
    TableStruct_graph_5fsnapshot_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::request::VertexAdj, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::request::VertexAdj, _impl_.tx_id_),
        PROTOBUF_FIELD_OFFSET(::request::VertexAdj, _impl_.out_),
        PROTOBUF_FIELD_OFFSET(::request::VertexAdj, _impl_.in_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::request::GraphSnapshot, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::request::GraphSnapshot, _impl_.node_id_),
        PROTOBUF_FIELD_OFFSET(::request::GraphSnapshot, _impl_.adj_),
        PROTOBUF_FIELD_OFFSET(::request::GraphSnapshot, _impl_.merged_order_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::request::MergedOrderHash, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::request::MergedOrderHash, _impl_.node_id_),
        PROTOBUF_FIELD_OFFSET(::request::MergedOrderHash, _impl_.hash_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::request::VertexAdj)},
        {9, sizeof(::request::GraphSnapshot)},
        {18, sizeof(::request::MergedOrderHash)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::request::_VertexAdj_default_instance_._instance,
    &::request::_GraphSnapshot_default_instance_._instance,
    &::request::_MergedOrderHash_default_instance_._instance,
};
const char descriptor_table_protodef_graph_5fsnapshot_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024graph_snapshot.proto\022\007request\"3\n\tVerte"
    "xAdj\022\r\n\005tx_id\030\001 \002(\t\022\013\n\003out\030\002 \003(\t\022\n\n\002in\030\003"
    " \003(\t\"k\n\rGraphSnapshot\022\017\n\007node_id\030\001 \002(\t\022\037"
    "\n\003adj\030\002 \003(\0132\022.request.VertexAdj\022(\n\014merge"
    "d_order\030\003 \003(\0132\022.request.VertexAdj\"0\n\017Mer"
    "gedOrderHash\022\017\n\007node_id\030\001 \002(\t\022\014\n\004hash\030\002 "
    "\002(\004"
};
static ::absl::once_flag descriptor_table_graph_5fsnapshot_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_graph_5fsnapshot_2eproto = {
    false,
    false,
    243,
    descriptor_table_protodef_graph_5fsnapshot_2eproto,
    "graph_snapshot.proto",
    &descriptor_table_graph_5fsnapshot_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_graph_5fsnapshot_2eproto::offsets,
    file_level_enum_descriptors_graph_5fsnapshot_2eproto,
    file_level_service_descriptors_graph_5fsnapshot_2eproto,
};
namespace request {
// ===================================================================

class VertexAdj::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<VertexAdj>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000004) ^ 0x00000004) != 0;
  }
};

VertexAdj::VertexAdj(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VertexAdj_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:request.VertexAdj)
}
PROTOBUF_NDEBUG_INLINE VertexAdj::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::request::VertexAdj& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        out_{visibility, arena, from.out_},
        in_{visibility, arena, from.in_},
        tx_id_(arena, from.tx_id_) {}

VertexAdj::VertexAdj(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VertexAdj& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VertexAdj_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VertexAdj* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:request.VertexAdj)
}
PROTOBUF_NDEBUG_INLINE VertexAdj::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        out_{visibility, arena},
        in_{visibility, arena},
        tx_id_(arena) {}

inline void VertexAdj::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
VertexAdj::~VertexAdj() {
  // @@protoc_insertion_point(destructor:request.VertexAdj)
  SharedDtor(*this);
}
inline void VertexAdj::SharedDtor(MessageLite& self) {
  VertexAdj& this_ = static_cast<VertexAdj&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.tx_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL VertexAdj::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VertexAdj(arena);
}
constexpr auto VertexAdj::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_.out_) +
          decltype(VertexAdj::_impl_.out_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_.in_) +
          decltype(VertexAdj::_impl_.in_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(VertexAdj), alignof(VertexAdj), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&VertexAdj::PlacementNew_,
                                 sizeof(VertexAdj),
                                 alignof(VertexAdj));
  }
}
constexpr auto VertexAdj::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_VertexAdj_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          VertexAdj::IsInitializedImpl,
          &VertexAdj::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<VertexAdj>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VertexAdj::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<VertexAdj>(), &VertexAdj::ByteSizeLong,
              &VertexAdj::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_._cached_size_),
          false,
      },
      &VertexAdj::kDescriptorMethods,
      &descriptor_table_graph_5fsnapshot_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VertexAdj_class_data_ =
        VertexAdj::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VertexAdj::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VertexAdj_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VertexAdj_class_data_.tc_table);
  return VertexAdj_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
VertexAdj::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    VertexAdj_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::request::VertexAdj>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required string tx_id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 2, 0,
      PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_.tx_id_)}},
    // repeated string out = 2;
    {::_pbi::TcParser::FastBR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_.out_)}},
    // repeated string in = 3;
    {::_pbi::TcParser::FastBR1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_.in_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string tx_id = 1;
    {PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_.tx_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated string out = 2;
    {PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_.out_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // repeated string in = 3;
    {PROTOBUF_FIELD_OFFSET(VertexAdj, _impl_.in_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void VertexAdj::Clear() {
// @@protoc_insertion_point(message_clear_start:request.VertexAdj)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.out_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.in_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.tx_id_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VertexAdj::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VertexAdj& this_ = static_cast<const VertexAdj&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VertexAdj::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VertexAdj& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:request.VertexAdj)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required string tx_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_tx_id();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated string out = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_out_size(); i < n; ++i) {
      const auto& s = this_._internal_out().Get(i);
      target = stream->WriteString(2, s, target);
    }
  }

  // repeated string in = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (int i = 0, n = this_._internal_in_size(); i < n; ++i) {
      const auto& s = this_._internal_in().Get(i);
      target = stream->WriteString(3, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:request.VertexAdj)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VertexAdj::ByteSizeLong(const MessageLite& base) {
  const VertexAdj& this_ = static_cast<const VertexAdj&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VertexAdj::ByteSizeLong() const {
  const VertexAdj& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:request.VertexAdj)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated string out = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_out().size());
      for (int i = 0, n = this_._internal_out().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_out().Get(i));
      }
    }
    // repeated string in = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_in().size());
      for (int i = 0, n = this_._internal_in().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_in().Get(i));
      }
    }
  }
   {
    // required string tx_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_tx_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void VertexAdj::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<VertexAdj*>(&to_msg);
  auto& from = static_cast<const VertexAdj&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:request.VertexAdj)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_out()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_out());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_in()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_in());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_tx_id(from._internal_tx_id());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void VertexAdj::CopyFrom(const VertexAdj& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:request.VertexAdj)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool VertexAdj::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const VertexAdj&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void VertexAdj::InternalSwap(VertexAdj* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.out_.InternalSwap(&other->_impl_.out_);
  _impl_.in_.InternalSwap(&other->_impl_.in_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tx_id_, &other->_impl_.tx_id_, arena);
}

::google::protobuf::Metadata VertexAdj::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GraphSnapshot::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GraphSnapshot>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000004) ^ 0x00000004) != 0;
  }
};

GraphSnapshot::GraphSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GraphSnapshot_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:request.GraphSnapshot)
}
PROTOBUF_NDEBUG_INLINE GraphSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::request::GraphSnapshot& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        adj_{visibility, arena, from.adj_},
        merged_order_{visibility, arena, from.merged_order_},
        node_id_(arena, from.node_id_) {}

GraphSnapshot::GraphSnapshot(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GraphSnapshot& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GraphSnapshot_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GraphSnapshot* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:request.GraphSnapshot)
}
PROTOBUF_NDEBUG_INLINE GraphSnapshot::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        adj_{visibility, arena},
        merged_order_{visibility, arena},
        node_id_(arena) {}

inline void GraphSnapshot::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GraphSnapshot::~GraphSnapshot() {
  // @@protoc_insertion_point(destructor:request.GraphSnapshot)
  SharedDtor(*this);
}
inline void GraphSnapshot::SharedDtor(MessageLite& self) {
  GraphSnapshot& this_ = static_cast<GraphSnapshot&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.node_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GraphSnapshot::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GraphSnapshot(arena);
}
constexpr auto GraphSnapshot::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_.adj_) +
          decltype(GraphSnapshot::_impl_.adj_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_.merged_order_) +
          decltype(GraphSnapshot::_impl_.merged_order_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(GraphSnapshot), alignof(GraphSnapshot), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&GraphSnapshot::PlacementNew_,
                                 sizeof(GraphSnapshot),
                                 alignof(GraphSnapshot));
  }
}
constexpr auto GraphSnapshot::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GraphSnapshot_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          GraphSnapshot::IsInitializedImpl,
          &GraphSnapshot::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GraphSnapshot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GraphSnapshot::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GraphSnapshot>(), &GraphSnapshot::ByteSizeLong,
              &GraphSnapshot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_._cached_size_),
          false,
      },
      &GraphSnapshot::kDescriptorMethods,
      &descriptor_table_graph_5fsnapshot_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GraphSnapshot_class_data_ =
        GraphSnapshot::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GraphSnapshot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GraphSnapshot_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GraphSnapshot_class_data_.tc_table);
  return GraphSnapshot_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2>
GraphSnapshot::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GraphSnapshot_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::request::GraphSnapshot>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required string node_id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 2, 0,
      PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_.node_id_)}},
    // repeated .request.VertexAdj adj = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_.adj_)}},
    // repeated .request.VertexAdj merged_order = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 1, 1,
      PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_.merged_order_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string node_id = 1;
    {PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_.node_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated .request.VertexAdj adj = 2;
    {PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_.adj_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .request.VertexAdj merged_order = 3;
    {PROTOBUF_FIELD_OFFSET(GraphSnapshot, _impl_.merged_order_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::request::VertexAdj>()},
      {::_pbi::TcParser::GetTable<::request::VertexAdj>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void GraphSnapshot::Clear() {
// @@protoc_insertion_point(message_clear_start:request.GraphSnapshot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.adj_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.merged_order_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.node_id_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GraphSnapshot::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GraphSnapshot& this_ = static_cast<const GraphSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GraphSnapshot::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GraphSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:request.GraphSnapshot)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required string node_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_node_id();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .request.VertexAdj adj = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_adj_size());
         i < n; i++) {
      const auto& repfield = this_._internal_adj().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated .request.VertexAdj merged_order = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_merged_order_size());
         i < n; i++) {
      const auto& repfield = this_._internal_merged_order().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              3, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:request.GraphSnapshot)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GraphSnapshot::ByteSizeLong(const MessageLite& base) {
  const GraphSnapshot& this_ = static_cast<const GraphSnapshot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GraphSnapshot::ByteSizeLong() const {
  const GraphSnapshot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:request.GraphSnapshot)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .request.VertexAdj adj = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_adj_size();
      for (const auto& msg : this_._internal_adj()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .request.VertexAdj merged_order = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_merged_order_size();
      for (const auto& msg : this_._internal_merged_order()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
   {
    // required string node_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_node_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GraphSnapshot::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GraphSnapshot*>(&to_msg);
  auto& from = static_cast<const GraphSnapshot&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:request.GraphSnapshot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_adj()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_adj());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_merged_order()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_merged_order());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_node_id(from._internal_node_id());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GraphSnapshot::CopyFrom(const GraphSnapshot& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:request.GraphSnapshot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GraphSnapshot::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const GraphSnapshot&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_adj()))
    return false;
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_merged_order()))
    return false;
  return true;
}

void GraphSnapshot::InternalSwap(GraphSnapshot* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.adj_.InternalSwap(&other->_impl_.adj_);
  _impl_.merged_order_.InternalSwap(&other->_impl_.merged_order_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.node_id_, &other->_impl_.node_id_, arena);
}

::google::protobuf::Metadata GraphSnapshot::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MergedOrderHash::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MergedOrderHash>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MergedOrderHash, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

MergedOrderHash::MergedOrderHash(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MergedOrderHash_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:request.MergedOrderHash)
}
PROTOBUF_NDEBUG_INLINE MergedOrderHash::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::request::MergedOrderHash& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        node_id_(arena, from.node_id_) {}

MergedOrderHash::MergedOrderHash(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MergedOrderHash& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MergedOrderHash_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MergedOrderHash* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.hash_ = from._impl_.hash_;

  // @@protoc_insertion_point(copy_constructor:request.MergedOrderHash)
}
PROTOBUF_NDEBUG_INLINE MergedOrderHash::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        node_id_(arena) {}

inline void MergedOrderHash::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.hash_ = {};
}
MergedOrderHash::~MergedOrderHash() {
  // @@protoc_insertion_point(destructor:request.MergedOrderHash)
  SharedDtor(*this);
}
inline void MergedOrderHash::SharedDtor(MessageLite& self) {
  MergedOrderHash& this_ = static_cast<MergedOrderHash&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.node_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MergedOrderHash::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MergedOrderHash(arena);
}
constexpr auto MergedOrderHash::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MergedOrderHash),
                                            alignof(MergedOrderHash));
}
constexpr auto MergedOrderHash::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MergedOrderHash_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          MergedOrderHash::IsInitializedImpl,
          &MergedOrderHash::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MergedOrderHash>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MergedOrderHash::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MergedOrderHash>(), &MergedOrderHash::ByteSizeLong,
              &MergedOrderHash::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MergedOrderHash, _impl_._cached_size_),
          false,
      },
      &MergedOrderHash::kDescriptorMethods,
      &descriptor_table_graph_5fsnapshot_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MergedOrderHash_class_data_ =
        MergedOrderHash::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MergedOrderHash::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MergedOrderHash_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MergedOrderHash_class_data_.tc_table);
  return MergedOrderHash_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
MergedOrderHash::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MergedOrderHash, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MergedOrderHash_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::request::MergedOrderHash>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required uint64 hash = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MergedOrderHash, _impl_.hash_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(MergedOrderHash, _impl_.hash_)}},
    // required string node_id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(MergedOrderHash, _impl_.node_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string node_id = 1;
    {PROTOBUF_FIELD_OFFSET(MergedOrderHash, _impl_.node_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // required uint64 hash = 2;
    {PROTOBUF_FIELD_OFFSET(MergedOrderHash, _impl_.hash_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void MergedOrderHash::Clear() {
// @@protoc_insertion_point(message_clear_start:request.MergedOrderHash)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.node_id_.ClearNonDefaultToEmpty();
  }
  _impl_.hash_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MergedOrderHash::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MergedOrderHash& this_ = static_cast<const MergedOrderHash&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MergedOrderHash::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MergedOrderHash& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:request.MergedOrderHash)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required string node_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_node_id();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // required uint64 hash = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this_._internal_hash(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:request.MergedOrderHash)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MergedOrderHash::ByteSizeLong(const MessageLite& base) {
  const MergedOrderHash& this_ = static_cast<const MergedOrderHash&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MergedOrderHash::ByteSizeLong() const {
  const MergedOrderHash& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:request.MergedOrderHash)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // required string node_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_node_id());
    }
    // required uint64 hash = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_hash());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MergedOrderHash::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MergedOrderHash*>(&to_msg);
  auto& from = static_cast<const MergedOrderHash&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:request.MergedOrderHash)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_node_id(from._internal_node_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.hash_ = from._impl_.hash_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MergedOrderHash::CopyFrom(const MergedOrderHash& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:request.MergedOrderHash)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MergedOrderHash::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const MergedOrderHash&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void MergedOrderHash::InternalSwap(MergedOrderHash* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.node_id_, &other->_impl_.node_id_, arena);
  swap(_impl_.hash_, other->_impl_.hash_);
}

::google::protobuf::Metadata MergedOrderHash::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace request
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_graph_5fsnapshot_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
