// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph_snapshot.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_graph_5fsnapshot_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_graph_5fsnapshot_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_graph_5fsnapshot_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_graph_5fsnapshot_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_graph_5fsnapshot_2eproto;
namespace request {
class GraphSnapshot;
class GraphSnapshotDefaultTypeInternal;
extern GraphSnapshotDefaultTypeInternal _GraphSnapshot_default_instance_;
class MergedOrderHash;
class MergedOrderHashDefaultTypeInternal;
extern MergedOrderHashDefaultTypeInternal _MergedOrderHash_default_instance_;
class VertexAdj;
class VertexAdjDefaultTypeInternal;
extern VertexAdjDefaultTypeInternal _VertexAdj_default_instance_;
}  // namespace request
PROTOBUF_NAMESPACE_OPEN
template<> ::request::GraphSnapshot* Arena::CreateMaybeMessage<::request::GraphSnapshot>(Arena*);
template<> ::request::MergedOrderHash* Arena::CreateMaybeMessage<::request::MergedOrderHash>(Arena*);
template<> ::request::VertexAdj* Arena::CreateMaybeMessage<::request::VertexAdj>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace request {

// ===================================================================

class VertexAdj PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:request.VertexAdj) */ {
 public:
  inline VertexAdj() : VertexAdj(nullptr) {};
  virtual ~VertexAdj();

  VertexAdj(const VertexAdj& from);
  VertexAdj(VertexAdj&& from) noexcept
    : VertexAdj() {
    *this = ::std::move(from);
  }

  inline VertexAdj& operator=(const VertexAdj& from) {
    CopyFrom(from);
    return *this;
  }
  inline VertexAdj& operator=(VertexAdj&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VertexAdj& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VertexAdj* internal_default_instance() {
    return reinterpret_cast<const VertexAdj*>(
               &_VertexAdj_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VertexAdj& a, VertexAdj& b) {
    a.Swap(&b);
  }
  inline void Swap(VertexAdj* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VertexAdj* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VertexAdj* New() const final {
    return CreateMaybeMessage<VertexAdj>(nullptr);
  }

  VertexAdj* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VertexAdj>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VertexAdj& from);
  void MergeFrom(const VertexAdj& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VertexAdj* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "request.VertexAdj";
  }
  protected:
  explicit VertexAdj(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_5fsnapshot_2eproto);
    return ::descriptor_table_graph_5fsnapshot_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOutFieldNumber = 2,
    kInFieldNumber = 3,
    kTxIdFieldNumber = 1,
  };
  // repeated string out = 2;
  int out_size() const;
  private:
  int _internal_out_size() const;
  public:
  void clear_out();
  const std::string& out(int index) const;
  std::string* mutable_out(int index);
  void set_out(int index, const std::string& value);
  void set_out(int index, std::string&& value);
  void set_out(int index, const char* value);
  void set_out(int index, const char* value, size_t size);
  std::string* add_out();
  void add_out(const std::string& value);
  void add_out(std::string&& value);
  void add_out(const char* value);
  void add_out(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& out() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_out();
  private:
  const std::string& _internal_out(int index) const;
  std::string* _internal_add_out();
  public:

  // repeated string in = 3;
  int in_size() const;
  private:
  int _internal_in_size() const;
  public:
  void clear_in();
  const std::string& in(int index) const;
  std::string* mutable_in(int index);
  void set_in(int index, const std::string& value);
  void set_in(int index, std::string&& value);
  void set_in(int index, const char* value);
  void set_in(int index, const char* value, size_t size);
  std::string* add_in();
  void add_in(const std::string& value);
  void add_in(std::string&& value);
  void add_in(const char* value);
  void add_in(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& in() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_in();
  private:
  const std::string& _internal_in(int index) const;
  std::string* _internal_add_in();
  public:

  // required string tx_id = 1;
  bool has_tx_id() const;
  private:
  bool _internal_has_tx_id() const;
  public:
  void clear_tx_id();
  const std::string& tx_id() const;
  void set_tx_id(const std::string& value);
  void set_tx_id(std::string&& value);
  void set_tx_id(const char* value);
  void set_tx_id(const char* value, size_t size);
  std::string* mutable_tx_id();
  std::string* release_tx_id();
  void set_allocated_tx_id(std::string* tx_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_tx_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_tx_id(
      std::string* tx_id);
  private:
  const std::string& _internal_tx_id() const;
  void _internal_set_tx_id(const std::string& value);
  std::string* _internal_mutable_tx_id();
  public:

  // @@protoc_insertion_point(class_scope:request.VertexAdj)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> out_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> in_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tx_id_;
  friend struct ::TableStruct_graph_5fsnapshot_2eproto;
};
// -------------------------------------------------------------------

class GraphSnapshot PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:request.GraphSnapshot) */ {
 public:
  inline GraphSnapshot() : GraphSnapshot(nullptr) {};
  virtual ~GraphSnapshot();

  GraphSnapshot(const GraphSnapshot& from);
  GraphSnapshot(GraphSnapshot&& from) noexcept
    : GraphSnapshot() {
    *this = ::std::move(from);
  }

  inline GraphSnapshot& operator=(const GraphSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphSnapshot& operator=(GraphSnapshot&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GraphSnapshot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GraphSnapshot* internal_default_instance() {
    return reinterpret_cast<const GraphSnapshot*>(
               &_GraphSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GraphSnapshot& a, GraphSnapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphSnapshot* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphSnapshot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraphSnapshot* New() const final {
    return CreateMaybeMessage<GraphSnapshot>(nullptr);
  }

  GraphSnapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraphSnapshot>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GraphSnapshot& from);
  void MergeFrom(const GraphSnapshot& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphSnapshot* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "request.GraphSnapshot";
  }
  protected:
  explicit GraphSnapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_5fsnapshot_2eproto);
    return ::descriptor_table_graph_5fsnapshot_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAdjFieldNumber = 2,
    kMergedOrderFieldNumber = 3,
    kNodeIdFieldNumber = 1,
  };
  // repeated .request.VertexAdj adj = 2;
  int adj_size() const;
  private:
  int _internal_adj_size() const;
  public:
  void clear_adj();
  ::request::VertexAdj* mutable_adj(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj >*
      mutable_adj();
  private:
  const ::request::VertexAdj& _internal_adj(int index) const;
  ::request::VertexAdj* _internal_add_adj();
  public:
  const ::request::VertexAdj& adj(int index) const;
  ::request::VertexAdj* add_adj();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj >&
      adj() const;

  // repeated .request.VertexAdj merged_order = 3;
  int merged_order_size() const;
  private:
  int _internal_merged_order_size() const;
  public:
  void clear_merged_order();
  ::request::VertexAdj* mutable_merged_order(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj >*
      mutable_merged_order();
  private:
  const ::request::VertexAdj& _internal_merged_order(int index) const;
  ::request::VertexAdj* _internal_add_merged_order();
  public:
  const ::request::VertexAdj& merged_order(int index) const;
  ::request::VertexAdj* add_merged_order();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj >&
      merged_order() const;

  // required string node_id = 1;
  bool has_node_id() const;
  private:
  bool _internal_has_node_id() const;
  public:
  void clear_node_id();
  const std::string& node_id() const;
  void set_node_id(const std::string& value);
  void set_node_id(std::string&& value);
  void set_node_id(const char* value);
  void set_node_id(const char* value, size_t size);
  std::string* mutable_node_id();
  std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_node_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_node_id(
      std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // @@protoc_insertion_point(class_scope:request.GraphSnapshot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj > adj_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj > merged_order_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
  friend struct ::TableStruct_graph_5fsnapshot_2eproto;
};
// -------------------------------------------------------------------

class MergedOrderHash PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:request.MergedOrderHash) */ {
 public:
  inline MergedOrderHash() : MergedOrderHash(nullptr) {};
  virtual ~MergedOrderHash();

  MergedOrderHash(const MergedOrderHash& from);
  MergedOrderHash(MergedOrderHash&& from) noexcept
    : MergedOrderHash() {
    *this = ::std::move(from);
  }

  inline MergedOrderHash& operator=(const MergedOrderHash& from) {
    CopyFrom(from);
    return *this;
  }
  inline MergedOrderHash& operator=(MergedOrderHash&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MergedOrderHash& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MergedOrderHash* internal_default_instance() {
    return reinterpret_cast<const MergedOrderHash*>(
               &_MergedOrderHash_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MergedOrderHash& a, MergedOrderHash& b) {
    a.Swap(&b);
  }
  inline void Swap(MergedOrderHash* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MergedOrderHash* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MergedOrderHash* New() const final {
    return CreateMaybeMessage<MergedOrderHash>(nullptr);
  }

  MergedOrderHash* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MergedOrderHash>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MergedOrderHash& from);
  void MergeFrom(const MergedOrderHash& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MergedOrderHash* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "request.MergedOrderHash";
  }
  protected:
  explicit MergedOrderHash(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_5fsnapshot_2eproto);
    return ::descriptor_table_graph_5fsnapshot_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 1,
    kHashFieldNumber = 2,
  };
  // required string node_id = 1;
  bool has_node_id() const;
  private:
  bool _internal_has_node_id() const;
  public:
  void clear_node_id();
  const std::string& node_id() const;
  void set_node_id(const std::string& value);
  void set_node_id(std::string&& value);
  void set_node_id(const char* value);
  void set_node_id(const char* value, size_t size);
  std::string* mutable_node_id();
  std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_node_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_node_id(
      std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // required uint64 hash = 2;
  bool has_hash() const;
  private:
  bool _internal_has_hash() const;
  public:
  void clear_hash();
  ::PROTOBUF_NAMESPACE_ID::uint64 hash() const;
  void set_hash(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_hash() const;
  void _internal_set_hash(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:request.MergedOrderHash)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 hash_;
  friend struct ::TableStruct_graph_5fsnapshot_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VertexAdj

// required string tx_id = 1;
inline bool VertexAdj::_internal_has_tx_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool VertexAdj::has_tx_id() const {
  return _internal_has_tx_id();
}
inline void VertexAdj::clear_tx_id() {
  tx_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& VertexAdj::tx_id() const {
  // @@protoc_insertion_point(field_get:request.VertexAdj.tx_id)
  return _internal_tx_id();
}
inline void VertexAdj::set_tx_id(const std::string& value) {
  _internal_set_tx_id(value);
  // @@protoc_insertion_point(field_set:request.VertexAdj.tx_id)
}
inline std::string* VertexAdj::mutable_tx_id() {
  // @@protoc_insertion_point(field_mutable:request.VertexAdj.tx_id)
  return _internal_mutable_tx_id();
}
inline const std::string& VertexAdj::_internal_tx_id() const {
  return tx_id_.Get();
}
inline void VertexAdj::_internal_set_tx_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  tx_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void VertexAdj::set_tx_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  tx_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:request.VertexAdj.tx_id)
}
inline void VertexAdj::set_tx_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  tx_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:request.VertexAdj.tx_id)
}
inline void VertexAdj::set_tx_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  tx_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:request.VertexAdj.tx_id)
}
inline std::string* VertexAdj::_internal_mutable_tx_id() {
  _has_bits_[0] |= 0x00000001u;
  return tx_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* VertexAdj::release_tx_id() {
  // @@protoc_insertion_point(field_release:request.VertexAdj.tx_id)
  if (!_internal_has_tx_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return tx_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VertexAdj::set_allocated_tx_id(std::string* tx_id) {
  if (tx_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  tx_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tx_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:request.VertexAdj.tx_id)
}
inline std::string* VertexAdj::unsafe_arena_release_tx_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.VertexAdj.tx_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return tx_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void VertexAdj::unsafe_arena_set_allocated_tx_id(
    std::string* tx_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (tx_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  tx_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      tx_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.VertexAdj.tx_id)
}

// repeated string out = 2;
inline int VertexAdj::_internal_out_size() const {
  return out_.size();
}
inline int VertexAdj::out_size() const {
  return _internal_out_size();
}
inline void VertexAdj::clear_out() {
  out_.Clear();
}
inline std::string* VertexAdj::add_out() {
  // @@protoc_insertion_point(field_add_mutable:request.VertexAdj.out)
  return _internal_add_out();
}
inline const std::string& VertexAdj::_internal_out(int index) const {
  return out_.Get(index);
}
inline const std::string& VertexAdj::out(int index) const {
  // @@protoc_insertion_point(field_get:request.VertexAdj.out)
  return _internal_out(index);
}
inline std::string* VertexAdj::mutable_out(int index) {
  // @@protoc_insertion_point(field_mutable:request.VertexAdj.out)
  return out_.Mutable(index);
}
inline void VertexAdj::set_out(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:request.VertexAdj.out)
  out_.Mutable(index)->assign(value);
}
inline void VertexAdj::set_out(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:request.VertexAdj.out)
  out_.Mutable(index)->assign(std::move(value));
}
inline void VertexAdj::set_out(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  out_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:request.VertexAdj.out)
}
inline void VertexAdj::set_out(int index, const char* value, size_t size) {
  out_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:request.VertexAdj.out)
}
inline std::string* VertexAdj::_internal_add_out() {
  return out_.Add();
}
inline void VertexAdj::add_out(const std::string& value) {
  out_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:request.VertexAdj.out)
}
inline void VertexAdj::add_out(std::string&& value) {
  out_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:request.VertexAdj.out)
}
inline void VertexAdj::add_out(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  out_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:request.VertexAdj.out)
}
inline void VertexAdj::add_out(const char* value, size_t size) {
  out_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:request.VertexAdj.out)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
VertexAdj::out() const {
  // @@protoc_insertion_point(field_list:request.VertexAdj.out)
  return out_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
VertexAdj::mutable_out() {
  // @@protoc_insertion_point(field_mutable_list:request.VertexAdj.out)
  return &out_;
}

// repeated string in = 3;
inline int VertexAdj::_internal_in_size() const {
  return in_.size();
}
inline int VertexAdj::in_size() const {
  return _internal_in_size();
}
inline void VertexAdj::clear_in() {
  in_.Clear();
}
inline std::string* VertexAdj::add_in() {
  // @@protoc_insertion_point(field_add_mutable:request.VertexAdj.in)
  return _internal_add_in();
}
inline const std::string& VertexAdj::_internal_in(int index) const {
  return in_.Get(index);
}
inline const std::string& VertexAdj::in(int index) const {
  // @@protoc_insertion_point(field_get:request.VertexAdj.in)
  return _internal_in(index);
}
inline std::string* VertexAdj::mutable_in(int index) {
  // @@protoc_insertion_point(field_mutable:request.VertexAdj.in)
  return in_.Mutable(index);
}
inline void VertexAdj::set_in(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:request.VertexAdj.in)
  in_.Mutable(index)->assign(value);
}
inline void VertexAdj::set_in(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:request.VertexAdj.in)
  in_.Mutable(index)->assign(std::move(value));
}
inline void VertexAdj::set_in(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  in_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:request.VertexAdj.in)
}
inline void VertexAdj::set_in(int index, const char* value, size_t size) {
  in_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:request.VertexAdj.in)
}
inline std::string* VertexAdj::_internal_add_in() {
  return in_.Add();
}
inline void VertexAdj::add_in(const std::string& value) {
  in_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:request.VertexAdj.in)
}
inline void VertexAdj::add_in(std::string&& value) {
  in_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:request.VertexAdj.in)
}
inline void VertexAdj::add_in(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  in_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:request.VertexAdj.in)
}
inline void VertexAdj::add_in(const char* value, size_t size) {
  in_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:request.VertexAdj.in)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
VertexAdj::in() const {
  // @@protoc_insertion_point(field_list:request.VertexAdj.in)
  return in_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
VertexAdj::mutable_in() {
  // @@protoc_insertion_point(field_mutable_list:request.VertexAdj.in)
  return &in_;
}

// -------------------------------------------------------------------

// GraphSnapshot

// required string node_id = 1;
inline bool GraphSnapshot::_internal_has_node_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GraphSnapshot::has_node_id() const {
  return _internal_has_node_id();
}
inline void GraphSnapshot::clear_node_id() {
  node_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& GraphSnapshot::node_id() const {
  // @@protoc_insertion_point(field_get:request.GraphSnapshot.node_id)
  return _internal_node_id();
}
inline void GraphSnapshot::set_node_id(const std::string& value) {
  _internal_set_node_id(value);
  // @@protoc_insertion_point(field_set:request.GraphSnapshot.node_id)
}
inline std::string* GraphSnapshot::mutable_node_id() {
  // @@protoc_insertion_point(field_mutable:request.GraphSnapshot.node_id)
  return _internal_mutable_node_id();
}
inline const std::string& GraphSnapshot::_internal_node_id() const {
  return node_id_.Get();
}
inline void GraphSnapshot::_internal_set_node_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GraphSnapshot::set_node_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  node_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:request.GraphSnapshot.node_id)
}
inline void GraphSnapshot::set_node_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:request.GraphSnapshot.node_id)
}
inline void GraphSnapshot::set_node_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:request.GraphSnapshot.node_id)
}
inline std::string* GraphSnapshot::_internal_mutable_node_id() {
  _has_bits_[0] |= 0x00000001u;
  return node_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GraphSnapshot::release_node_id() {
  // @@protoc_insertion_point(field_release:request.GraphSnapshot.node_id)
  if (!_internal_has_node_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return node_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GraphSnapshot::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  node_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), node_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:request.GraphSnapshot.node_id)
}
inline std::string* GraphSnapshot::unsafe_arena_release_node_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.GraphSnapshot.node_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return node_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GraphSnapshot::unsafe_arena_set_allocated_node_id(
    std::string* node_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (node_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  node_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      node_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.GraphSnapshot.node_id)
}

// repeated .request.VertexAdj adj = 2;
inline int GraphSnapshot::_internal_adj_size() const {
  return adj_.size();
}
inline int GraphSnapshot::adj_size() const {
  return _internal_adj_size();
}
inline void GraphSnapshot::clear_adj() {
  adj_.Clear();
}
inline ::request::VertexAdj* GraphSnapshot::mutable_adj(int index) {
  // @@protoc_insertion_point(field_mutable:request.GraphSnapshot.adj)
  return adj_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj >*
GraphSnapshot::mutable_adj() {
  // @@protoc_insertion_point(field_mutable_list:request.GraphSnapshot.adj)
  return &adj_;
}
inline const ::request::VertexAdj& GraphSnapshot::_internal_adj(int index) const {
  return adj_.Get(index);
}
inline const ::request::VertexAdj& GraphSnapshot::adj(int index) const {
  // @@protoc_insertion_point(field_get:request.GraphSnapshot.adj)
  return _internal_adj(index);
}
inline ::request::VertexAdj* GraphSnapshot::_internal_add_adj() {
  return adj_.Add();
}
inline ::request::VertexAdj* GraphSnapshot::add_adj() {
  // @@protoc_insertion_point(field_add:request.GraphSnapshot.adj)
  return _internal_add_adj();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj >&
GraphSnapshot::adj() const {
  // @@protoc_insertion_point(field_list:request.GraphSnapshot.adj)
  return adj_;
}

// repeated .request.VertexAdj merged_order = 3;
inline int GraphSnapshot::_internal_merged_order_size() const {
  return merged_order_.size();
}
inline int GraphSnapshot::merged_order_size() const {
  return _internal_merged_order_size();
}
inline void GraphSnapshot::clear_merged_order() {
  merged_order_.Clear();
}
inline ::request::VertexAdj* GraphSnapshot::mutable_merged_order(int index) {
  // @@protoc_insertion_point(field_mutable:request.GraphSnapshot.merged_order)
  return merged_order_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj >*
GraphSnapshot::mutable_merged_order() {
  // @@protoc_insertion_point(field_mutable_list:request.GraphSnapshot.merged_order)
  return &merged_order_;
}
inline const ::request::VertexAdj& GraphSnapshot::_internal_merged_order(int index) const {
  return merged_order_.Get(index);
}
inline const ::request::VertexAdj& GraphSnapshot::merged_order(int index) const {
  // @@protoc_insertion_point(field_get:request.GraphSnapshot.merged_order)
  return _internal_merged_order(index);
}
inline ::request::VertexAdj* GraphSnapshot::_internal_add_merged_order() {
  return merged_order_.Add();
}
inline ::request::VertexAdj* GraphSnapshot::add_merged_order() {
  // @@protoc_insertion_point(field_add:request.GraphSnapshot.merged_order)
  return _internal_add_merged_order();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::request::VertexAdj >&
GraphSnapshot::merged_order() const {
  // @@protoc_insertion_point(field_list:request.GraphSnapshot.merged_order)
  return merged_order_;
}

// -------------------------------------------------------------------

// MergedOrderHash

// required string node_id = 1;
inline bool MergedOrderHash::_internal_has_node_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MergedOrderHash::has_node_id() const {
  return _internal_has_node_id();
}
inline void MergedOrderHash::clear_node_id() {
  node_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MergedOrderHash::node_id() const {
  // @@protoc_insertion_point(field_get:request.MergedOrderHash.node_id)
  return _internal_node_id();
}
inline void MergedOrderHash::set_node_id(const std::string& value) {
  _internal_set_node_id(value);
  // @@protoc_insertion_point(field_set:request.MergedOrderHash.node_id)
}
inline std::string* MergedOrderHash::mutable_node_id() {
  // @@protoc_insertion_point(field_mutable:request.MergedOrderHash.node_id)
  return _internal_mutable_node_id();
}
inline const std::string& MergedOrderHash::_internal_node_id() const {
  return node_id_.Get();
}
inline void MergedOrderHash::_internal_set_node_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MergedOrderHash::set_node_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  node_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:request.MergedOrderHash.node_id)
}
inline void MergedOrderHash::set_node_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:request.MergedOrderHash.node_id)
}
inline void MergedOrderHash::set_node_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  node_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:request.MergedOrderHash.node_id)
}
inline std::string* MergedOrderHash::_internal_mutable_node_id() {
  _has_bits_[0] |= 0x00000001u;
  return node_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MergedOrderHash::release_node_id() {
  // @@protoc_insertion_point(field_release:request.MergedOrderHash.node_id)
  if (!_internal_has_node_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return node_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MergedOrderHash::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  node_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), node_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:request.MergedOrderHash.node_id)
}
inline std::string* MergedOrderHash::unsafe_arena_release_node_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:request.MergedOrderHash.node_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return node_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void MergedOrderHash::unsafe_arena_set_allocated_node_id(
    std::string* node_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (node_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  node_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      node_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:request.MergedOrderHash.node_id)
}

// required uint64 hash = 2;
inline bool MergedOrderHash::_internal_has_hash() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool MergedOrderHash::has_hash() const {
  return _internal_has_hash();
}
inline void MergedOrderHash::clear_hash() {
  hash_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MergedOrderHash::_internal_hash() const {
  return hash_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MergedOrderHash::hash() const {
  // @@protoc_insertion_point(field_get:request.MergedOrderHash.hash)
  return _internal_hash();
}
inline void MergedOrderHash::_internal_set_hash(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  hash_ = value;
}
inline void MergedOrderHash::set_hash(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_hash(value);
  // @@protoc_insertion_point(field_set:request.MergedOrderHash.hash)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace request

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_graph_5fsnapshot_2eproto
