// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: graph_snapshot.proto
// Protobuf C++ Version: 6.33.4

#ifndef graph_5fsnapshot_2eproto_2epb_2eh
#define graph_5fsnapshot_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_graph_5fsnapshot_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_graph_5fsnapshot_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_graph_5fsnapshot_2eproto;
}  // extern "C"
namespace request {
class GraphSnapshot;
struct GraphSnapshotDefaultTypeInternal;
extern GraphSnapshotDefaultTypeInternal _GraphSnapshot_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GraphSnapshot_class_data_;
class VertexAdj;
struct VertexAdjDefaultTypeInternal;
extern VertexAdjDefaultTypeInternal _VertexAdj_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull VertexAdj_class_data_;
}  // namespace request
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace request {

// ===================================================================


// -------------------------------------------------------------------

class VertexAdj final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:request.VertexAdj) */ {
 public:
  inline VertexAdj() : VertexAdj(nullptr) {}
  ~VertexAdj() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VertexAdj* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VertexAdj));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VertexAdj(::google::protobuf::internal::ConstantInitialized);

  inline VertexAdj(const VertexAdj& from) : VertexAdj(nullptr, from) {}
  inline VertexAdj(VertexAdj&& from) noexcept
      : VertexAdj(nullptr, ::std::move(from)) {}
  inline VertexAdj& operator=(const VertexAdj& from) {
    CopyFrom(from);
    return *this;
  }
  inline VertexAdj& operator=(VertexAdj&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VertexAdj& default_instance() {
    return *reinterpret_cast<const VertexAdj*>(
        &_VertexAdj_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VertexAdj& a, VertexAdj& b) { a.Swap(&b); }
  inline void Swap(VertexAdj* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VertexAdj* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VertexAdj* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VertexAdj>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VertexAdj& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VertexAdj& from) { VertexAdj::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VertexAdj* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "request.VertexAdj"; }

  explicit VertexAdj(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VertexAdj(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VertexAdj& from);
  VertexAdj(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VertexAdj&& from) noexcept
      : VertexAdj(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOutFieldNumber = 2,
    kInFieldNumber = 3,
    kTxIdFieldNumber = 1,
  };
  // repeated string out = 2;
  int out_size() const;
  private:
  int _internal_out_size() const;

  public:
  void clear_out() ;
  const ::std::string& out(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_out(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_out(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_out();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_out(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& out() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_out();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_out() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_out();

  public:
  // repeated string in = 3;
  int in_size() const;
  private:
  int _internal_in_size() const;

  public:
  void clear_in() ;
  const ::std::string& in(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_in(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_in(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_in();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_in(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& in() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_in();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_in() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_in();

  public:
  // required string tx_id = 1;
  bool has_tx_id() const;
  void clear_tx_id() ;
  const ::std::string& tx_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tx_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_tx_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_tx_id();
  void set_allocated_tx_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_tx_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tx_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_tx_id();

  public:
  // @@protoc_insertion_point(class_scope:request.VertexAdj)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const VertexAdj& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> out_;
    ::google::protobuf::RepeatedPtrField<::std::string> in_;
    ::google::protobuf::internal::ArenaStringPtr tx_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_graph_5fsnapshot_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull VertexAdj_class_data_;
// -------------------------------------------------------------------

class GraphSnapshot final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:request.GraphSnapshot) */ {
 public:
  inline GraphSnapshot() : GraphSnapshot(nullptr) {}
  ~GraphSnapshot() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GraphSnapshot* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GraphSnapshot));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GraphSnapshot(::google::protobuf::internal::ConstantInitialized);

  inline GraphSnapshot(const GraphSnapshot& from) : GraphSnapshot(nullptr, from) {}
  inline GraphSnapshot(GraphSnapshot&& from) noexcept
      : GraphSnapshot(nullptr, ::std::move(from)) {}
  inline GraphSnapshot& operator=(const GraphSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphSnapshot& operator=(GraphSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GraphSnapshot& default_instance() {
    return *reinterpret_cast<const GraphSnapshot*>(
        &_GraphSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GraphSnapshot& a, GraphSnapshot& b) { a.Swap(&b); }
  inline void Swap(GraphSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GraphSnapshot* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GraphSnapshot>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GraphSnapshot& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GraphSnapshot& from) { GraphSnapshot::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GraphSnapshot* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "request.GraphSnapshot"; }

  explicit GraphSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GraphSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GraphSnapshot& from);
  GraphSnapshot(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GraphSnapshot&& from) noexcept
      : GraphSnapshot(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAdjFieldNumber = 2,
    kMergedOrderFieldNumber = 3,
    kNodeIdFieldNumber = 1,
  };
  // repeated .request.VertexAdj adj = 2;
  int adj_size() const;
  private:
  int _internal_adj_size() const;

  public:
  void clear_adj() ;
  ::request::VertexAdj* PROTOBUF_NONNULL mutable_adj(int index);
  ::google::protobuf::RepeatedPtrField<::request::VertexAdj>* PROTOBUF_NONNULL mutable_adj();

  private:
  const ::google::protobuf::RepeatedPtrField<::request::VertexAdj>& _internal_adj() const;
  ::google::protobuf::RepeatedPtrField<::request::VertexAdj>* PROTOBUF_NONNULL _internal_mutable_adj();
  public:
  const ::request::VertexAdj& adj(int index) const;
  ::request::VertexAdj* PROTOBUF_NONNULL add_adj();
  const ::google::protobuf::RepeatedPtrField<::request::VertexAdj>& adj() const;
  // repeated .request.VertexAdj merged_order = 3;
  int merged_order_size() const;
  private:
  int _internal_merged_order_size() const;

  public:
  void clear_merged_order() ;
  ::request::VertexAdj* PROTOBUF_NONNULL mutable_merged_order(int index);
  ::google::protobuf::RepeatedPtrField<::request::VertexAdj>* PROTOBUF_NONNULL mutable_merged_order();

  private:
  const ::google::protobuf::RepeatedPtrField<::request::VertexAdj>& _internal_merged_order() const;
  ::google::protobuf::RepeatedPtrField<::request::VertexAdj>* PROTOBUF_NONNULL _internal_mutable_merged_order();
  public:
  const ::request::VertexAdj& merged_order(int index) const;
  ::request::VertexAdj* PROTOBUF_NONNULL add_merged_order();
  const ::google::protobuf::RepeatedPtrField<::request::VertexAdj>& merged_order() const;
  // required string node_id = 1;
  bool has_node_id() const;
  void clear_node_id() ;
  const ::std::string& node_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_node_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_node_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_node_id();
  void set_allocated_node_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_node_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_node_id();

  public:
  // @@protoc_insertion_point(class_scope:request.GraphSnapshot)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GraphSnapshot& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::request::VertexAdj > adj_;
    ::google::protobuf::RepeatedPtrField< ::request::VertexAdj > merged_order_;
    ::google::protobuf::internal::ArenaStringPtr node_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_graph_5fsnapshot_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GraphSnapshot_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VertexAdj

// required string tx_id = 1;
inline bool VertexAdj::has_tx_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void VertexAdj::clear_tx_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& VertexAdj::tx_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.VertexAdj.tx_id)
  return _internal_tx_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VertexAdj::set_tx_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.tx_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:request.VertexAdj.tx_id)
}
inline ::std::string* PROTOBUF_NONNULL VertexAdj::mutable_tx_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_tx_id();
  // @@protoc_insertion_point(field_mutable:request.VertexAdj.tx_id)
  return _s;
}
inline const ::std::string& VertexAdj::_internal_tx_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_id_.Get();
}
inline void VertexAdj::_internal_set_tx_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VertexAdj::_internal_mutable_tx_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tx_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VertexAdj::release_tx_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:request.VertexAdj.tx_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.tx_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tx_id_.Set("", GetArena());
  }
  return released;
}
inline void VertexAdj::set_allocated_tx_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.tx_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tx_id_.IsDefault()) {
    _impl_.tx_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:request.VertexAdj.tx_id)
}

// repeated string out = 2;
inline int VertexAdj::_internal_out_size() const {
  return _internal_out().size();
}
inline int VertexAdj::out_size() const {
  return _internal_out_size();
}
inline void VertexAdj::clear_out() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.out_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL VertexAdj::add_out()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_out()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:request.VertexAdj.out)
  return _s;
}
inline const ::std::string& VertexAdj::out(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.VertexAdj.out)
  return _internal_out().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL VertexAdj::mutable_out(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:request.VertexAdj.out)
  return _internal_mutable_out()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void VertexAdj::set_out(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_out()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:request.VertexAdj.out)
}
template <typename Arg_, typename... Args_>
inline void VertexAdj::add_out(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_out(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:request.VertexAdj.out)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& VertexAdj::out()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:request.VertexAdj.out)
  return _internal_out();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
VertexAdj::mutable_out() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:request.VertexAdj.out)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_out();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
VertexAdj::_internal_out() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.out_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
VertexAdj::_internal_mutable_out() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.out_;
}

// repeated string in = 3;
inline int VertexAdj::_internal_in_size() const {
  return _internal_in().size();
}
inline int VertexAdj::in_size() const {
  return _internal_in_size();
}
inline void VertexAdj::clear_in() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.in_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::std::string* PROTOBUF_NONNULL VertexAdj::add_in()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_in()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add_mutable:request.VertexAdj.in)
  return _s;
}
inline const ::std::string& VertexAdj::in(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.VertexAdj.in)
  return _internal_in().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL VertexAdj::mutable_in(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:request.VertexAdj.in)
  return _internal_mutable_in()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void VertexAdj::set_in(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_in()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:request.VertexAdj.in)
}
template <typename Arg_, typename... Args_>
inline void VertexAdj::add_in(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_in(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:request.VertexAdj.in)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& VertexAdj::in()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:request.VertexAdj.in)
  return _internal_in();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
VertexAdj::mutable_in() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:request.VertexAdj.in)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_in();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
VertexAdj::_internal_in() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.in_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
VertexAdj::_internal_mutable_in() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.in_;
}

// -------------------------------------------------------------------

// GraphSnapshot

// required string node_id = 1;
inline bool GraphSnapshot::has_node_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void GraphSnapshot::clear_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& GraphSnapshot::node_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.GraphSnapshot.node_id)
  return _internal_node_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GraphSnapshot::set_node_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.node_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:request.GraphSnapshot.node_id)
}
inline ::std::string* PROTOBUF_NONNULL GraphSnapshot::mutable_node_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:request.GraphSnapshot.node_id)
  return _s;
}
inline const ::std::string& GraphSnapshot::_internal_node_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.node_id_.Get();
}
inline void GraphSnapshot::_internal_set_node_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GraphSnapshot::_internal_mutable_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.node_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GraphSnapshot::release_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:request.GraphSnapshot.node_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.node_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.node_id_.Set("", GetArena());
  }
  return released;
}
inline void GraphSnapshot::set_allocated_node_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.node_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:request.GraphSnapshot.node_id)
}

// repeated .request.VertexAdj adj = 2;
inline int GraphSnapshot::_internal_adj_size() const {
  return _internal_adj().size();
}
inline int GraphSnapshot::adj_size() const {
  return _internal_adj_size();
}
inline void GraphSnapshot::clear_adj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.adj_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::request::VertexAdj* PROTOBUF_NONNULL GraphSnapshot::mutable_adj(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:request.GraphSnapshot.adj)
  return _internal_mutable_adj()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::request::VertexAdj>* PROTOBUF_NONNULL GraphSnapshot::mutable_adj()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:request.GraphSnapshot.adj)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_adj();
}
inline const ::request::VertexAdj& GraphSnapshot::adj(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.GraphSnapshot.adj)
  return _internal_adj().Get(index);
}
inline ::request::VertexAdj* PROTOBUF_NONNULL GraphSnapshot::add_adj()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::request::VertexAdj* _add =
      _internal_mutable_adj()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:request.GraphSnapshot.adj)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::request::VertexAdj>& GraphSnapshot::adj() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:request.GraphSnapshot.adj)
  return _internal_adj();
}
inline const ::google::protobuf::RepeatedPtrField<::request::VertexAdj>&
GraphSnapshot::_internal_adj() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.adj_;
}
inline ::google::protobuf::RepeatedPtrField<::request::VertexAdj>* PROTOBUF_NONNULL
GraphSnapshot::_internal_mutable_adj() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.adj_;
}

// repeated .request.VertexAdj merged_order = 3;
inline int GraphSnapshot::_internal_merged_order_size() const {
  return _internal_merged_order().size();
}
inline int GraphSnapshot::merged_order_size() const {
  return _internal_merged_order_size();
}
inline void GraphSnapshot::clear_merged_order() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.merged_order_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::request::VertexAdj* PROTOBUF_NONNULL GraphSnapshot::mutable_merged_order(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:request.GraphSnapshot.merged_order)
  return _internal_mutable_merged_order()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::request::VertexAdj>* PROTOBUF_NONNULL GraphSnapshot::mutable_merged_order()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:request.GraphSnapshot.merged_order)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_merged_order();
}
inline const ::request::VertexAdj& GraphSnapshot::merged_order(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.GraphSnapshot.merged_order)
  return _internal_merged_order().Get(index);
}
inline ::request::VertexAdj* PROTOBUF_NONNULL GraphSnapshot::add_merged_order()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::request::VertexAdj* _add =
      _internal_mutable_merged_order()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:request.GraphSnapshot.merged_order)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::request::VertexAdj>& GraphSnapshot::merged_order() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:request.GraphSnapshot.merged_order)
  return _internal_merged_order();
}
inline const ::google::protobuf::RepeatedPtrField<::request::VertexAdj>&
GraphSnapshot::_internal_merged_order() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.merged_order_;
}
inline ::google::protobuf::RepeatedPtrField<::request::VertexAdj>* PROTOBUF_NONNULL
GraphSnapshot::_internal_mutable_merged_order() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.merged_order_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace request


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // graph_5fsnapshot_2eproto_2epb_2eh
