// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: request.proto
// Protobuf C++ Version: 6.33.4

#ifndef request_2eproto_2epb_2eh
#define request_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_request_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_request_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_request_2eproto;
}  // extern "C"
namespace request {
enum Operation_OperationType : int;
extern const uint32_t Operation_OperationType_internal_data_[];
enum Request_RequestRecipient : int;
extern const uint32_t Request_RequestRecipient_internal_data_[];
class Operation;
struct OperationDefaultTypeInternal;
extern OperationDefaultTypeInternal _Operation_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Operation_class_data_;
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Request_class_data_;
class Transaction;
struct TransactionDefaultTypeInternal;
extern TransactionDefaultTypeInternal _Transaction_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Transaction_class_data_;
}  // namespace request
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::request::Operation_OperationType_internal_data_>
    internal::EnumTraitsImpl::value<::request::Operation_OperationType>;
template <>
internal::EnumTraitsT<::request::Request_RequestRecipient_internal_data_>
    internal::EnumTraitsImpl::value<::request::Request_RequestRecipient>;
}  // namespace protobuf
}  // namespace google

namespace request {
enum Operation_OperationType : int {
  Operation_OperationType_READ = 0,
  Operation_OperationType_WRITE = 1,
};

extern const uint32_t Operation_OperationType_internal_data_[];
inline constexpr Operation_OperationType Operation_OperationType_OperationType_MIN =
    static_cast<Operation_OperationType>(0);
inline constexpr Operation_OperationType Operation_OperationType_OperationType_MAX =
    static_cast<Operation_OperationType>(1);
inline bool Operation_OperationType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int Operation_OperationType_OperationType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Operation_OperationType_descriptor();
template <typename T>
const ::std::string& Operation_OperationType_Name(T value) {
  static_assert(::std::is_same<T, Operation_OperationType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to OperationType_Name().");
  return Operation_OperationType_Name(static_cast<Operation_OperationType>(value));
}
template <>
inline const ::std::string& Operation_OperationType_Name(Operation_OperationType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Operation_OperationType_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool Operation_OperationType_Parse(
    ::absl::string_view name, Operation_OperationType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Operation_OperationType>(Operation_OperationType_descriptor(), name,
                                           value);
}
enum Request_RequestRecipient : int {
  Request_RequestRecipient_BATCHER = 0,
  Request_RequestRecipient_PARTIAL = 1,
  Request_RequestRecipient_MERGER = 3,
  Request_RequestRecipient_PING = 4,
  Request_RequestRecipient_START = 5,
  Request_RequestRecipient_READY = 6,
  Request_RequestRecipient_MERGED = 7,
  Request_RequestRecipient_MERGED_HASH = 8,
};

extern const uint32_t Request_RequestRecipient_internal_data_[];
inline constexpr Request_RequestRecipient Request_RequestRecipient_RequestRecipient_MIN =
    static_cast<Request_RequestRecipient>(0);
inline constexpr Request_RequestRecipient Request_RequestRecipient_RequestRecipient_MAX =
    static_cast<Request_RequestRecipient>(8);
inline bool Request_RequestRecipient_IsValid(int value) {
  return 0 <= value && value <= 8 && ((507u >> value) & 1) != 0;
}
inline constexpr int Request_RequestRecipient_RequestRecipient_ARRAYSIZE = 8 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Request_RequestRecipient_descriptor();
template <typename T>
const ::std::string& Request_RequestRecipient_Name(T value) {
  static_assert(::std::is_same<T, Request_RequestRecipient>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RequestRecipient_Name().");
  return Request_RequestRecipient_Name(static_cast<Request_RequestRecipient>(value));
}
template <>
inline const ::std::string& Request_RequestRecipient_Name(Request_RequestRecipient value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Request_RequestRecipient_descriptor, 0, 8>(
      static_cast<int>(value));
}
inline bool Request_RequestRecipient_Parse(
    ::absl::string_view name, Request_RequestRecipient* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Request_RequestRecipient>(Request_RequestRecipient_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Operation final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:request.Operation) */ {
 public:
  inline Operation() : Operation(nullptr) {}
  ~Operation() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Operation* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Operation));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Operation(::google::protobuf::internal::ConstantInitialized);

  inline Operation(const Operation& from) : Operation(nullptr, from) {}
  inline Operation(Operation&& from) noexcept
      : Operation(nullptr, ::std::move(from)) {}
  inline Operation& operator=(const Operation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Operation& operator=(Operation&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Operation& default_instance() {
    return *reinterpret_cast<const Operation*>(
        &_Operation_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Operation& a, Operation& b) { a.Swap(&b); }
  inline void Swap(Operation* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Operation* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Operation* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Operation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Operation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Operation& from) { Operation::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Operation* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "request.Operation"; }

  explicit Operation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Operation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Operation& from);
  Operation(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Operation&& from) noexcept
      : Operation(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using OperationType = Operation_OperationType;
  static constexpr OperationType READ = Operation_OperationType_READ;
  static constexpr OperationType WRITE = Operation_OperationType_WRITE;
  static inline bool OperationType_IsValid(int value) {
    return Operation_OperationType_IsValid(value);
  }
  static constexpr OperationType OperationType_MIN = Operation_OperationType_OperationType_MIN;
  static constexpr OperationType OperationType_MAX = Operation_OperationType_OperationType_MAX;
  static constexpr int OperationType_ARRAYSIZE = Operation_OperationType_OperationType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL OperationType_descriptor() {
    return Operation_OperationType_descriptor();
  }
  template <typename T>
  static inline const ::std::string& OperationType_Name(T value) {
    return Operation_OperationType_Name(value);
  }
  static inline bool OperationType_Parse(
      ::absl::string_view name, OperationType* PROTOBUF_NONNULL value) {
    return Operation_OperationType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kKeyFieldNumber = 2,
    kValueFieldNumber = 3,
    kTypeFieldNumber = 1,
  };
  // required string key = 2;
  bool has_key() const;
  void clear_key() ;
  const ::std::string& key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_key();
  void set_allocated_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_key();

  public:
  // optional string value = 3;
  bool has_value() const;
  void clear_value() ;
  const ::std::string& value() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_value();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_value();
  void set_allocated_value(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_value(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_value();

  public:
  // required .request.Operation.OperationType type = 1;
  bool has_type() const;
  void clear_type() ;
  ::request::Operation_OperationType type() const;
  void set_type(::request::Operation_OperationType value);

  private:
  ::request::Operation_OperationType _internal_type() const;
  void _internal_set_type(::request::Operation_OperationType value);

  public:
  // @@protoc_insertion_point(class_scope:request.Operation)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Operation& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr key_;
    ::google::protobuf::internal::ArenaStringPtr value_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_request_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Operation_class_data_;
// -------------------------------------------------------------------

class Transaction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:request.Transaction) */ {
 public:
  inline Transaction() : Transaction(nullptr) {}
  ~Transaction() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Transaction* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Transaction));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Transaction(::google::protobuf::internal::ConstantInitialized);

  inline Transaction(const Transaction& from) : Transaction(nullptr, from) {}
  inline Transaction(Transaction&& from) noexcept
      : Transaction(nullptr, ::std::move(from)) {}
  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }
  inline Transaction& operator=(Transaction&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Transaction& default_instance() {
    return *reinterpret_cast<const Transaction*>(
        &_Transaction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Transaction& a, Transaction& b) { a.Swap(&b); }
  inline void Swap(Transaction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Transaction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Transaction* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Transaction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Transaction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Transaction& from) { Transaction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Transaction* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "request.Transaction"; }

  explicit Transaction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Transaction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Transaction& from);
  Transaction(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Transaction&& from) noexcept
      : Transaction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOperationsFieldNumber = 3,
    kOrderFieldNumber = 1,
    kIdFieldNumber = 2,
    kClientIdFieldNumber = 4,
    kRandomStampFieldNumber = 5,
  };
  // repeated .request.Operation operations = 3;
  int operations_size() const;
  private:
  int _internal_operations_size() const;

  public:
  void clear_operations() ;
  ::request::Operation* PROTOBUF_NONNULL mutable_operations(int index);
  ::google::protobuf::RepeatedPtrField<::request::Operation>* PROTOBUF_NONNULL mutable_operations();

  private:
  const ::google::protobuf::RepeatedPtrField<::request::Operation>& _internal_operations() const;
  ::google::protobuf::RepeatedPtrField<::request::Operation>* PROTOBUF_NONNULL _internal_mutable_operations();
  public:
  const ::request::Operation& operations(int index) const;
  ::request::Operation* PROTOBUF_NONNULL add_operations();
  const ::google::protobuf::RepeatedPtrField<::request::Operation>& operations() const;
  // optional string order = 1;
  bool has_order() const;
  void clear_order() ;
  const ::std::string& order() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_order(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_order();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_order();
  void set_allocated_order(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_order() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_order(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_order();

  public:
  // required string id = 2;
  bool has_id() const;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // optional int32 client_id = 4;
  bool has_client_id() const;
  void clear_client_id() ;
  ::int32_t client_id() const;
  void set_client_id(::int32_t value);

  private:
  ::int32_t _internal_client_id() const;
  void _internal_set_client_id(::int32_t value);

  public:
  // optional int32 random_stamp = 5;
  bool has_random_stamp() const;
  void clear_random_stamp() ;
  ::int32_t random_stamp() const;
  void set_random_stamp(::int32_t value);

  private:
  ::int32_t _internal_random_stamp() const;
  void _internal_set_random_stamp(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:request.Transaction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Transaction& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::request::Operation > operations_;
    ::google::protobuf::internal::ArenaStringPtr order_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::int32_t client_id_;
    ::int32_t random_stamp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_request_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Transaction_class_data_;
// -------------------------------------------------------------------

class Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:request.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Request(::google::protobuf::internal::ConstantInitialized);

  inline Request(const Request& from) : Request(nullptr, from) {}
  inline Request(Request&& from) noexcept
      : Request(nullptr, ::std::move(from)) {}
  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *reinterpret_cast<const Request*>(
        &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Request& a, Request& b) { a.Swap(&b); }
  inline void Swap(Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Request& from) { Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "request.Request"; }

  explicit Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Request& from);
  Request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Request&& from) noexcept
      : Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using RequestRecipient = Request_RequestRecipient;
  static constexpr RequestRecipient BATCHER = Request_RequestRecipient_BATCHER;
  static constexpr RequestRecipient PARTIAL = Request_RequestRecipient_PARTIAL;
  static constexpr RequestRecipient MERGER = Request_RequestRecipient_MERGER;
  static constexpr RequestRecipient PING = Request_RequestRecipient_PING;
  static constexpr RequestRecipient START = Request_RequestRecipient_START;
  static constexpr RequestRecipient READY = Request_RequestRecipient_READY;
  static constexpr RequestRecipient MERGED = Request_RequestRecipient_MERGED;
  static constexpr RequestRecipient MERGED_HASH = Request_RequestRecipient_MERGED_HASH;
  static inline bool RequestRecipient_IsValid(int value) {
    return Request_RequestRecipient_IsValid(value);
  }
  static constexpr RequestRecipient RequestRecipient_MIN = Request_RequestRecipient_RequestRecipient_MIN;
  static constexpr RequestRecipient RequestRecipient_MAX = Request_RequestRecipient_RequestRecipient_MAX;
  static constexpr int RequestRecipient_ARRAYSIZE = Request_RequestRecipient_RequestRecipient_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RequestRecipient_descriptor() {
    return Request_RequestRecipient_descriptor();
  }
  template <typename T>
  static inline const ::std::string& RequestRecipient_Name(T value) {
    return Request_RequestRecipient_Name(value);
  }
  static inline bool RequestRecipient_Parse(
      ::absl::string_view name, RequestRecipient* PROTOBUF_NONNULL value) {
    return Request_RequestRecipient_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kTransactionFieldNumber = 3,
    kClientIdFieldNumber = 1,
    kServerIdFieldNumber = 2,
    kRecipientFieldNumber = 4,
    kRoundFieldNumber = 5,
    kTargetServerIdFieldNumber = 6,
    kBatcherRoundFieldNumber = 7,
  };
  // repeated .request.Transaction transaction = 3;
  int transaction_size() const;
  private:
  int _internal_transaction_size() const;

  public:
  void clear_transaction() ;
  ::request::Transaction* PROTOBUF_NONNULL mutable_transaction(int index);
  ::google::protobuf::RepeatedPtrField<::request::Transaction>* PROTOBUF_NONNULL mutable_transaction();

  private:
  const ::google::protobuf::RepeatedPtrField<::request::Transaction>& _internal_transaction() const;
  ::google::protobuf::RepeatedPtrField<::request::Transaction>* PROTOBUF_NONNULL _internal_mutable_transaction();
  public:
  const ::request::Transaction& transaction(int index) const;
  ::request::Transaction* PROTOBUF_NONNULL add_transaction();
  const ::google::protobuf::RepeatedPtrField<::request::Transaction>& transaction() const;
  // optional int32 client_id = 1;
  bool has_client_id() const;
  void clear_client_id() ;
  ::int32_t client_id() const;
  void set_client_id(::int32_t value);

  private:
  ::int32_t _internal_client_id() const;
  void _internal_set_client_id(::int32_t value);

  public:
  // optional int32 server_id = 2;
  bool has_server_id() const;
  void clear_server_id() ;
  ::int32_t server_id() const;
  void set_server_id(::int32_t value);

  private:
  ::int32_t _internal_server_id() const;
  void _internal_set_server_id(::int32_t value);

  public:
  // required .request.Request.RequestRecipient recipient = 4;
  bool has_recipient() const;
  void clear_recipient() ;
  ::request::Request_RequestRecipient recipient() const;
  void set_recipient(::request::Request_RequestRecipient value);

  private:
  ::request::Request_RequestRecipient _internal_recipient() const;
  void _internal_set_recipient(::request::Request_RequestRecipient value);

  public:
  // optional int32 round = 5;
  bool has_round() const;
  void clear_round() ;
  ::int32_t round() const;
  void set_round(::int32_t value);

  private:
  ::int32_t _internal_round() const;
  void _internal_set_round(::int32_t value);

  public:
  // optional int32 target_server_id = 6;
  bool has_target_server_id() const;
  void clear_target_server_id() ;
  ::int32_t target_server_id() const;
  void set_target_server_id(::int32_t value);

  private:
  ::int32_t _internal_target_server_id() const;
  void _internal_set_target_server_id(::int32_t value);

  public:
  // optional int32 batcher_round = 7;
  bool has_batcher_round() const;
  void clear_batcher_round() ;
  ::int32_t batcher_round() const;
  void set_batcher_round(::int32_t value);

  private:
  ::int32_t _internal_batcher_round() const;
  void _internal_set_batcher_round(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:request.Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::request::Transaction > transaction_;
    ::int32_t client_id_;
    ::int32_t server_id_;
    int recipient_;
    ::int32_t round_;
    ::int32_t target_server_id_;
    ::int32_t batcher_round_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_request_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Request_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Operation

// required .request.Operation.OperationType type = 1;
inline bool Operation::has_type() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Operation::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::request::Operation_OperationType Operation::type() const {
  // @@protoc_insertion_point(field_get:request.Operation.type)
  return _internal_type();
}
inline void Operation::set_type(::request::Operation_OperationType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:request.Operation.type)
}
inline ::request::Operation_OperationType Operation::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::request::Operation_OperationType>(_impl_.type_);
}
inline void Operation::_internal_set_type(::request::Operation_OperationType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::request::Operation_OperationType_internal_data_));
                                          _impl_.type_ = value;
}

// required string key = 2;
inline bool Operation::has_key() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Operation::clear_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Operation::key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.Operation.key)
  return _internal_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Operation::set_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:request.Operation.key)
}
inline ::std::string* PROTOBUF_NONNULL Operation::mutable_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:request.Operation.key)
  return _s;
}
inline const ::std::string& Operation::_internal_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.key_.Get();
}
inline void Operation::_internal_set_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Operation::_internal_mutable_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Operation::release_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:request.Operation.key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.key_.Set("", GetArena());
  }
  return released;
}
inline void Operation::set_allocated_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:request.Operation.key)
}

// optional string value = 3;
inline bool Operation::has_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Operation::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Operation::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.Operation.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Operation::set_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:request.Operation.value)
}
inline ::std::string* PROTOBUF_NONNULL Operation::mutable_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:request.Operation.value)
  return _s;
}
inline const ::std::string& Operation::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void Operation::_internal_set_value(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Operation::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Operation::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:request.Operation.value)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.value_.Set("", GetArena());
  }
  return released;
}
inline void Operation::set_allocated_value(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:request.Operation.value)
}

// -------------------------------------------------------------------

// Transaction

// optional string order = 1;
inline bool Transaction::has_order() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Transaction::clear_order() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Transaction::order() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.Transaction.order)
  return _internal_order();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_order(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.order_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:request.Transaction.order)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_order()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_order();
  // @@protoc_insertion_point(field_mutable:request.Transaction.order)
  return _s;
}
inline const ::std::string& Transaction::_internal_order() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.order_.Get();
}
inline void Transaction::_internal_set_order(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.order_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_order() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.order_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_order() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:request.Transaction.order)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.order_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.order_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_order(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.order_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.order_.IsDefault()) {
    _impl_.order_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:request.Transaction.order)
}

// required string id = 2;
inline bool Transaction::has_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Transaction::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& Transaction::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.Transaction.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Transaction::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:request.Transaction.id)
}
inline ::std::string* PROTOBUF_NONNULL Transaction::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:request.Transaction.id)
  return _s;
}
inline const ::std::string& Transaction::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void Transaction::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Transaction::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Transaction::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:request.Transaction.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void Transaction::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:request.Transaction.id)
}

// repeated .request.Operation operations = 3;
inline int Transaction::_internal_operations_size() const {
  return _internal_operations().size();
}
inline int Transaction::operations_size() const {
  return _internal_operations_size();
}
inline void Transaction::clear_operations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.operations_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::request::Operation* PROTOBUF_NONNULL Transaction::mutable_operations(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:request.Transaction.operations)
  return _internal_mutable_operations()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::request::Operation>* PROTOBUF_NONNULL Transaction::mutable_operations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:request.Transaction.operations)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_operations();
}
inline const ::request::Operation& Transaction::operations(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.Transaction.operations)
  return _internal_operations().Get(index);
}
inline ::request::Operation* PROTOBUF_NONNULL Transaction::add_operations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::request::Operation* _add =
      _internal_mutable_operations()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:request.Transaction.operations)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::request::Operation>& Transaction::operations() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:request.Transaction.operations)
  return _internal_operations();
}
inline const ::google::protobuf::RepeatedPtrField<::request::Operation>&
Transaction::_internal_operations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.operations_;
}
inline ::google::protobuf::RepeatedPtrField<::request::Operation>* PROTOBUF_NONNULL
Transaction::_internal_mutable_operations() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.operations_;
}

// optional int32 client_id = 4;
inline bool Transaction::has_client_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void Transaction::clear_client_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t Transaction::client_id() const {
  // @@protoc_insertion_point(field_get:request.Transaction.client_id)
  return _internal_client_id();
}
inline void Transaction::set_client_id(::int32_t value) {
  _internal_set_client_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:request.Transaction.client_id)
}
inline ::int32_t Transaction::_internal_client_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.client_id_;
}
inline void Transaction::_internal_set_client_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_id_ = value;
}

// optional int32 random_stamp = 5;
inline bool Transaction::has_random_stamp() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void Transaction::clear_random_stamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.random_stamp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t Transaction::random_stamp() const {
  // @@protoc_insertion_point(field_get:request.Transaction.random_stamp)
  return _internal_random_stamp();
}
inline void Transaction::set_random_stamp(::int32_t value) {
  _internal_set_random_stamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:request.Transaction.random_stamp)
}
inline ::int32_t Transaction::_internal_random_stamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.random_stamp_;
}
inline void Transaction::_internal_set_random_stamp(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.random_stamp_ = value;
}

// -------------------------------------------------------------------

// Request

// optional int32 client_id = 1;
inline bool Request::has_client_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Request::clear_client_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t Request::client_id() const {
  // @@protoc_insertion_point(field_get:request.Request.client_id)
  return _internal_client_id();
}
inline void Request::set_client_id(::int32_t value) {
  _internal_set_client_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:request.Request.client_id)
}
inline ::int32_t Request::_internal_client_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.client_id_;
}
inline void Request::_internal_set_client_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_id_ = value;
}

// optional int32 server_id = 2;
inline bool Request::has_server_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Request::clear_server_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t Request::server_id() const {
  // @@protoc_insertion_point(field_get:request.Request.server_id)
  return _internal_server_id();
}
inline void Request::set_server_id(::int32_t value) {
  _internal_set_server_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:request.Request.server_id)
}
inline ::int32_t Request::_internal_server_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_id_;
}
inline void Request::_internal_set_server_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_id_ = value;
}

// repeated .request.Transaction transaction = 3;
inline int Request::_internal_transaction_size() const {
  return _internal_transaction().size();
}
inline int Request::transaction_size() const {
  return _internal_transaction_size();
}
inline void Request::clear_transaction() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transaction_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::request::Transaction* PROTOBUF_NONNULL Request::mutable_transaction(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:request.Request.transaction)
  return _internal_mutable_transaction()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::request::Transaction>* PROTOBUF_NONNULL Request::mutable_transaction()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:request.Request.transaction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_transaction();
}
inline const ::request::Transaction& Request::transaction(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:request.Request.transaction)
  return _internal_transaction().Get(index);
}
inline ::request::Transaction* PROTOBUF_NONNULL Request::add_transaction()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::request::Transaction* _add =
      _internal_mutable_transaction()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:request.Request.transaction)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::request::Transaction>& Request::transaction() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:request.Request.transaction)
  return _internal_transaction();
}
inline const ::google::protobuf::RepeatedPtrField<::request::Transaction>&
Request::_internal_transaction() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.transaction_;
}
inline ::google::protobuf::RepeatedPtrField<::request::Transaction>* PROTOBUF_NONNULL
Request::_internal_mutable_transaction() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.transaction_;
}

// required .request.Request.RequestRecipient recipient = 4;
inline bool Request::has_recipient() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void Request::clear_recipient() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.recipient_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::request::Request_RequestRecipient Request::recipient() const {
  // @@protoc_insertion_point(field_get:request.Request.recipient)
  return _internal_recipient();
}
inline void Request::set_recipient(::request::Request_RequestRecipient value) {
  _internal_set_recipient(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:request.Request.recipient)
}
inline ::request::Request_RequestRecipient Request::_internal_recipient() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::request::Request_RequestRecipient>(_impl_.recipient_);
}
inline void Request::_internal_set_recipient(::request::Request_RequestRecipient value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::request::Request_RequestRecipient_internal_data_));
                                          _impl_.recipient_ = value;
}

// optional int32 round = 5;
inline bool Request::has_round() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void Request::clear_round() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.round_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t Request::round() const {
  // @@protoc_insertion_point(field_get:request.Request.round)
  return _internal_round();
}
inline void Request::set_round(::int32_t value) {
  _internal_set_round(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:request.Request.round)
}
inline ::int32_t Request::_internal_round() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.round_;
}
inline void Request::_internal_set_round(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.round_ = value;
}

// optional int32 target_server_id = 6;
inline bool Request::has_target_server_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void Request::clear_target_server_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_server_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t Request::target_server_id() const {
  // @@protoc_insertion_point(field_get:request.Request.target_server_id)
  return _internal_target_server_id();
}
inline void Request::set_target_server_id(::int32_t value) {
  _internal_set_target_server_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:request.Request.target_server_id)
}
inline ::int32_t Request::_internal_target_server_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_server_id_;
}
inline void Request::_internal_set_target_server_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_server_id_ = value;
}

// optional int32 batcher_round = 7;
inline bool Request::has_batcher_round() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void Request::clear_batcher_round() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batcher_round_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t Request::batcher_round() const {
  // @@protoc_insertion_point(field_get:request.Request.batcher_round)
  return _internal_batcher_round();
}
inline void Request::set_batcher_round(::int32_t value) {
  _internal_set_batcher_round(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:request.Request.batcher_round)
}
inline ::int32_t Request::_internal_batcher_round() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.batcher_round_;
}
inline void Request::_internal_set_batcher_round(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batcher_round_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace request


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::request::Operation_OperationType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::request::Operation_OperationType>() {
  return ::request::Operation_OperationType_descriptor();
}
template <>
struct is_proto_enum<::request::Request_RequestRecipient> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::request::Request_RequestRecipient>() {
  return ::request::Request_RequestRecipient_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // request_2eproto_2epb_2eh
